# Generated by Django 5.0.3 on 2024-03-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_count',
            field=models.IntegerField(default=0),
        ),
    ]
