# Generated by Django 5.0.3 on 2024-03-24 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_choice_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice_count',
        ),
    ]
